sources:
  - name: marketing_perf_source
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    description: Raw data from database in raw schema
    schema: raw

    tables:
      - name: website_sessions
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
      - name: orders
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
      - name: order_items
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
      - name: order_item_refunds
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
      - name: website_pages
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
      - name: products
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
