[sources.filesystem.credentials]
bucket_url = "/home/marcel/marketing-performance-analysis/data/"

[destination.snowflake.credentials]
database = "marketing_performance"
password = "nt56G5tBSXsuMCg"
username = "MARCELA"
host = "CYOSLBF-HW54784"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
